"use client";

import { useState, useEffect } from "react";

export interface Client {
  id: string;
  name: string;
  phone: string;
  whatsapp: string;
  location: string;
  district: string;
  age: number;
  gender: "male" | "female";
  housingStatus: string;
  children: number;
  grades: string;
  interests: string[];
  notes: string;
  staffId: string; // Tracks which staff registered this client
  createdAt: string;
}

export interface Interest {
  id: string;
  label: string;
  category: string;
}

export interface CustomField {
  id: string;
  label: string;
  type: "text" | "number" | "date" | "select";
  active: boolean;
}

export interface Staff {
  id: string;
  name: string;
  phone: string;
  password?: string;
  role: string;
  status: "Active" | "Suspended" | "On Call" | "Offline";
  rating: number;
  tasksDone: number;
  monthlyTasks: number;
  image: string;
  active: boolean;
}

const DEFAULT_INTERESTS: Interest[] = [
  { id: "i1", label: "سيارات هيونداي", category: "سيارات" },
  { id: "i2", label: "سيارات تويوتا", category: "سيارات" },
  { id: "i3", label: "تمويل عقاري", category: "عقارات" },
  { id: "i4", label: "تأمين طبي", category: "تأمين" },
];

const DEFAULT_FIELDS: CustomField[] = [
  { id: "f1", label: "رقم لوحة السيارة", type: "text", active: true },
  { id: "f2", label: "تاريخ البدء المتوقع", type: "date", active: false },
];

const DEFAULT_STAFF: Staff[] = [
  { 
    id: "S1", 
    name: "علي سالم حيدر", 
    phone: "77325854", 
    password: "123",
    role: "مدير مبيعات", 
    status: "Active", 
    rating: 4.9, 
    tasksDone: 0, 
    monthlyTasks: 0, 
    image: "https://i.pravatar.cc/150?u=ahmed",
    active: true
  },
  { 
    id: "S2", 
    name: "محمد علي", 
    phone: "770325852", 
    password: "456",
    role: "مندوب ميداني", 
    status: "Suspended", 
    rating: 4.5, 
    tasksDone: 0, 
    monthlyTasks: 0, 
    image: "https://i.pravatar.cc/150?u=mo" ,
    active: false
  },
];

export function useStore() {
  const [clients, setClients] = useState<Client[]>([]);
  const [staff, setStaff] = useState<Staff[]>([]);
  const [interests, setInterests] = useState<Interest[]>([]);
  const [fields, setFields] = useState<CustomField[]>([]);
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    const savedClients = localStorage.getItem("fieldpro_clients");
    const savedStaff = localStorage.getItem("fieldpro_staff");
    const savedInterests = localStorage.getItem("fieldpro_interests");
    const savedFields = localStorage.getItem("fieldpro_fields");

    let loadedStaff = DEFAULT_STAFF;
    if (savedStaff) {
      loadedStaff = JSON.parse(savedStaff);
    }
    setStaff(loadedStaff);

    // Dynamic resolution of Ali's exact ID, even if autogenerated by localStorage
    const aliTarget = loadedStaff.find((s: Staff) => s.name.includes("علي سالم")) || loadedStaff[0];
    const aliTargetId = aliTarget ? aliTarget.id : "S1";

    if (savedClients) {
      const parsed = JSON.parse(savedClients);
      // Migrates clients to Ali's ACTUAL dynamic ID inside this specific computer's localStorage
      const migrated = parsed.map((c: any) => {
          // If staffId is missing or hardcoded to S1 when S1 doesn't exist anymore, rewrite it
          if (!c.staffId || c.staffId === "S1") {
             return { ...c, staffId: aliTargetId };
          }
          return c;
      });
      setClients(migrated);
    }
    
    if (savedInterests) setInterests(JSON.parse(savedInterests)); else setInterests(DEFAULT_INTERESTS);
    if (savedFields) setFields(JSON.parse(savedFields)); else setFields(DEFAULT_FIELDS);
    
    setIsLoaded(true);
  }, []);

  const save = (key: string, data: any) => {
    localStorage.setItem(key, JSON.stringify(data));
  };

  // Client Management
  const addClient = (client: Omit<Client, "id" | "createdAt" | "staffId">, staffId?: string) => {
    // Determine dynamic staffId, specifically grabbing Ali's actual local ID
    const aliTarget = staff.find(s => s.name.includes("علي سالم")) || staff[0] || { id: 'S1' };
    const exactStaffId = staffId || aliTarget.id;

    const newClient: Client = {
      ...client,
      id: `REG-${Math.floor(Math.random() * 90000 + 10000)}`,
      staffId: exactStaffId,
      createdAt: new Date().toISOString()
    };
    const updated = [newClient, ...clients];
    setClients(updated);
    save("fieldpro_clients", updated);
    return newClient;
  };

  // Staff Management
  const addStaff = (member: Omit<Staff, "id">) => {
    const newMember: Staff = { ...member, id: `S${Date.now()}` };
    const updated = [...staff, newMember];
    setStaff(updated);
    save("fieldpro_staff", updated);
    return newMember;
  };

  const updateStaff = (id: string, updates: Partial<Staff>) => {
    const updated = staff.map(s => s.id === id ? { ...s, ...updates } : s);
    setStaff(updated);
    save("fieldpro_staff", updated);
  };

  const deleteStaff = (id: string) => {
    const updated = staff.filter(s => s.id !== id);
    setStaff(updated);
    save("fieldpro_staff", updated);
  };

  // Interest Management
  const addInterest = (label: string, category: string) => {
    const newInterest = { id: `i${Date.now()}`, label, category };
    const updated = [...interests, newInterest];
    setInterests(updated);
    save("fieldpro_interests", updated);
  };

  const updateInterest = (id: string, label: string, category: string) => {
    const updated = interests.map(i => i.id === id ? { ...i, label, category } : i);
    setInterests(updated);
    save("fieldpro_interests", updated);
  };

  const deleteInterest = (id: string) => {
    const updated = interests.filter(i => i.id !== id);
    setInterests(updated);
    save("fieldpro_interests", updated);
  };

  // Field Management
  const toggleField = (id: string) => {
    const updated = fields.map(f => f.id === id ? { ...f, active: !f.active } : f);
    setFields(updated);
    save("fieldpro_fields", updated);
  };

  const addField = (label: string, type: any) => {
    const newField = { id: `f${Date.now()}`, label, type, active: true };
    const updated = [...fields, newField];
    setFields(updated);
    save("fieldpro_fields", updated);
  };

  const updateField = (id: string, label: string, type: string) => {
    const updated = fields.map(f => f.id === id ? { ...f, label, type: type as any } : f);
    setFields(updated);
    save("fieldpro_fields", updated);
  };

  const deleteField = (id: string) => {
    const updated = fields.filter(f => f.id !== id);
    setFields(updated);
    save("fieldpro_fields", updated);
  };

  return { 
    clients, staff, interests, fields, 
    addClient, 
    addStaff, updateStaff, deleteStaff,
    addInterest, updateInterest, deleteInterest,
    toggleField, addField, updateField, deleteField,
    isLoaded 
  };
}

